"""Generate human-readable Markdown diagnosis reports."""

from datetime import datetime
from typing import Dict, List

from diagnosis.hepatology_kb import ABBREVIATIONS, REFERENCE_RANGES


def generate_report(
    diagnosis_result: Dict,
    lab_results: List[Dict],
) -> str:
    """Produce a Markdown-formatted clinical summary.

    Parameters
    ----------
    diagnosis_result:
        Output of ``diagnosis.engine.diagnose()``.
    lab_results:
        Original lab result dicts (``name``/``test`` + ``value`` + optional ``unit``).

    Returns
    -------
    str  Markdown report.
    """
    sections: List[str] = []

    # Header
    sections.append("# Clinical Diagnosis Report")
    sections.append(f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    sections.append("")

    # Overall severity banner
    severity = diagnosis_result.get("overall_severity", "normal")
    severity_emoji = {
        "critical": "CRITICAL",
        "severe": "SEVERE",
        "moderate": "MODERATE",
        "mild": "MILD",
        "normal": "NORMAL",
    }
    sections.append(f"**Overall Severity:** {severity_emoji.get(severity, severity.upper())}")
    sections.append("")

    # Lab values table
    sections.append("## Lab Results Summary")
    sections.append("")
    sections.append("| Test | Value | Unit | Reference Range | Status |")
    sections.append("|------|-------|------|-----------------|--------|")

    abnormal_names = {
        a["name"] for a in diagnosis_result.get("abnormal_values", [])
    }
    abnormal_lookup: Dict[str, str] = {
        a["name"]: a["status"]
        for a in diagnosis_result.get("abnormal_values", [])
    }

    for lab in lab_results:
        name = lab.get("name", lab.get("test", "")).strip()
        value = lab.get("value", "")
        unit = lab.get("unit", "")
        ref = REFERENCE_RANGES.get(name)
        ref_str = f"{ref[0]}-{ref[1]}" if ref else "-"
        status = abnormal_lookup.get(name, "Normal")
        marker = f"**{status}**" if name in abnormal_names else status
        sections.append(f"| {name} | {value} | {unit} | {ref_str} | {marker} |")

    sections.append("")

    # Abnormal values highlight
    abnormals = diagnosis_result.get("abnormal_values", [])
    if abnormals:
        sections.append("## Abnormal Values")
        sections.append("")
        for ab in abnormals:
            sections.append(
                f"- **{ab['name']}**: {ab['value']} "
                f"({ab['status']}, reference: {ab['reference_range']})"
            )
        sections.append("")

    # Differential diagnosis
    conditions = diagnosis_result.get("possible_conditions", [])
    if conditions:
        sections.append("## Differential Diagnosis")
        sections.append("")
        for i, cond in enumerate(conditions, 1):
            sections.append(
                f"### {i}. {cond['condition']} "
                f"(Severity: {cond['severity_score']}/10 - {cond['severity_label'].upper()})"
            )
            sections.append("")
            sections.append(cond["description"])
            sections.append("")
    else:
        sections.append("## Differential Diagnosis")
        sections.append("")
        sections.append("No specific hepatological conditions matched the provided lab values.")
        sections.append("")

    # Recommendations
    recommendations = diagnosis_result.get("recommendations", [])
    if recommendations:
        sections.append("## Recommended Actions")
        sections.append("")
        for rec in recommendations:
            sections.append(f"- {rec}")
        sections.append("")

    # LLM analysis (if present)
    llm_analysis = diagnosis_result.get("llm_analysis")
    if llm_analysis:
        sections.append("## AI-Augmented Analysis")
        sections.append("")
        sections.append(llm_analysis)
        sections.append("")

    # Abbreviations glossary
    sections.append("## Abbreviations")
    sections.append("")
    sections.append("| Abbreviation | Full Form |")
    sections.append("|--------------|-----------|")
    for abbr, full in sorted(ABBREVIATIONS.items()):
        sections.append(f"| {abbr} | {full} |")
    sections.append("")

    # Disclaimer
    sections.append("---")
    sections.append("")
    sections.append(
        "> **Disclaimer:** This report is generated by an AI-assisted diagnostic "
        "system and is intended for informational purposes only. It does **not** "
        "constitute medical advice, diagnosis, or treatment. All findings must be "
        "reviewed and validated by a qualified healthcare professional. Clinical "
        "decisions should not be based solely on this report."
    )
    sections.append("")

    return "\n".join(sections)
